name: "tails_active_retention"
version: "1.0.0"

profile: "tails_active_retention"

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tails_active_retention:
    +materialized: view
